config/routes.rb
Rails.application.routes.draw do
  
  get 'manage/products'

  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  get 'manage/index'

  resources :products
  resource :cart, only: [:show] 
  resources :order_items, only: [:create, :update, :destroy]
  resources :charges

  root to: "products#index"

  devise_for :users do
    get "/login" => "devise/sessions#new"
    get "/register" => "devise/registrations#new"
  end

   

get '/buy/:permalink', to: 'transactions#new', as: :show_buy 
post '/buy/:permalink', to: 'transactions#create', as: :buy
get  '/pickup/:guid',   to: 'transactions#pickup',   as: :pickup
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :order_items
  has_many :sales
  default_scope { where(active: true) }

  validates_numericality_of :price,
    greater_than: 0.49,
    message: "The smallest transaction amount Stripe allows is 50 cents, so we've limited the cost of one item to be at least 50 cents." 

  has_attached_file :photo, :styles => { :small => "150x150>" },
                  :url => "/assets/products/:id/:style/:basename.:extension", 
                  :path => ":rails_root/public/assets/products/:id/:style/:basename.:extension"
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @order_item = current_order.order_items.new
  end

  def new
    @product = Product.new
  end

  def create
    Product.create(product_params)
    redirect_to products_path
  end

  def edit
    @product = Product.find(params[:id])
  end
 
  def update
    @product = Product.find(params[:id])
    @product.update_attributes(product_params)
    redirect_to products_path
    @product.save!
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end
 
  private

  def product_params
    params.require(:product).permit(:name, :price, :description, :photo)
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description, size: '60x6' %>
  </div>
  <div>
    <% f.label :photo %>
    <%= f.file_field :photo %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<%end%>

app/views/products/_product_row.html.erb
<div class="well">
  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></small></h4>
    </div>
    <div class="col-xs-4">
      
      <%= form_for order_item, remote: true do |f| %>
      <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency product.price %></span></h4>
        <div class="input-group">
          <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
          <div class="input-group-btn">
            <%= f.hidden_field :product_id, value: product.id %>
            <%= f.submit "Add to Cart", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>
    
  </div>
</div>

app/views/products/edit.html.erb
<h2>Edit this product:</h2>
<%= render "form" %>
<h5><%= link_to 'Delete Posting', @product, method: :delete %></h5>

app/views/products/index.html.erb
<h3 class="text-center">Products for Sale</h3> 
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <% @products.each do |product| %>
        <%= render "product_row", product: product, order_item: @order_item, image_tag: product.photo.url(:small) %>
        <h5>
        <%= link_to "Edit Posting", edit_product_path(product)%>
        </h5>
      <% end %>
    </div>
  </div>

app/views/products/manage.html.erb
<% @products.each do |product| %>
  <h3><%= product.title %></h3>
  <p><%= product.description %></p>
  <h5><%= link_to "Edit Listing", edit_product_path(product)%></h5>
<% end %>

app/views/products/new.html.erb
<h1>Add a Product</h1>

<%= render "form" %>