config/routes.rb
Rails.application.routes.draw do
  
  get 'manage/products'

  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  get 'manage/index'

  resources :products
  resource :cart, only: [:show] 
  resources :order_items, only: [:create, :update, :destroy]
  resources :charges

  root to: "products#index"

  devise_for :users do
    get "/login" => "devise/sessions#new"
    get "/register" => "devise/registrations#new"
  end

   

get '/buy/:permalink', to: 'transactions#new', as: :show_buy 
post '/buy/:permalink', to: 'transactions#create', as: :buy
get  '/pickup/:guid',   to: 'transactions#pickup',   as: :pickup
end

app/views/layouts/_alerts.html.erb
<%if notice.present? || alert.present? %>
  <div class="row">
    <%is_alert = alert.present? ? "alert" : ""%>
      <div data-alert class="alert-box <%=is_alert%>">
        <%=notice || alert%>
        <a href="#" class="close">&times;</a>
      </div>
  </div>
<%end%>

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-link" %>

app/views/layouts/_footer.html.erb
<div class="footer"> 
<Hr>
<p align=center>
Hydraulic Electro Service Corp<br>
 9910 Edes Avenue Oakland, CA 94603 <br>
Open 7:30 am - 4:30 pm, Mondays-Fridays, except holidays.<Br>
Please call: (510) 654-4641
</p>
</div>

app/views/layouts/_header.html.erb
<center>
          <%if signed_in?%>
            <div id="logo"><%=link_to "Logout", destroy_user_session_path, method: :delete%> * <%=link_to "View Account", edit_user_registration_path%></div>
         <%else%>
           <div id="logo"><%=link_to "Register", new_user_registration_path, :class => 'navbar-link' %></div> <div id=logo><%=link_to "Login", new_user_session_path, :class => 'navbar-link' %></div>
        <%end%>
        <br />        
      <br />
         <div id="logo">
           <%= image_tag("HydraulicElectroLogo.jpg", :alt => "Hydraulic Electro Services, Inc.", width: "750", height: "180", class: "displayed") %>
</p>      </div>
 </div>
</center>    

app/views/layouts/application.html.erb
<!DOCTYPE html> <html> <head>
  <title>Hydraulic Electro</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <% if request.ssl? %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <% else %>
    <%= stylesheet_link_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <% end %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %> 
</head> 

<header>
  <%= render "layouts/header" %>
 
</header>
<body>
  <div id=block>
  <%= render "layouts/alerts" %>
  <%= render 'layouts/cart_text' %>
  <br /> 
  <%= yield %>
</div>
   <%= render "layouts/footer" %> 
  </body> 
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html> <html> <head> </head> <body>
  <%= yield %> </body> </html>
<%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>